### ISSUE TITLE
cookies are not shared between extension and dialog

### ISSUE THREAD

**Issue by tjallingt** [tableau/extensions-api#123]
I would expect the extension and the dialogs that it is displaying to share the same cookies (cookiejar?), but it appears that this is not the case. Is this correct?
This makes authorizing and tracking users of extensions very difficult.

**Comment by Kovner** [comment]
Good catch. We will investigate.

**Comment by craigbloodworth** [comment]
I'd say this is expected behaviour for Desktop? There's no local persistence storage other then the workbook XML but that's OK because one workbook = one user. Can't you just use:
```
tableau.extensions.settings.set();
tableau.extensions.settings.saveAsync();
```
to store the session info in Desktop?

That method won't work in Server as most server users won't be editing the workbook, they'll just be using the extension. In that case you can use cookies as the browser is responsible for everything and just use the variable:
`tableau.extensions.environment.context`
to detect if the workbook is being run in Server or Desktop

**Comment by johnDance** [comment]
@tjallingt - This work has been done, but needs to get into the release pipeline. The plan is for it to be part of 2020.4. When released, non-persistent cookies and localstorage will be available to extensions. They will be accessible to extensions from the same domain, as they are on server. They will persist as long as Tableau is running. When Tableau is terminated, the cookies & localstorage will be cleared.
