### ISSUE TITLE
Registration Failed: XSD Validation Failed: file:

### ISSUE THREAD

**Issue by dkhungry** [tableau/extensions-api#126]
I just updated to the beta 2 client, did a new clone of the repo, and installed node v8.11.2.  I'm attempting to look at the DataSources sample extension under the Samples folder.  After install and starting the node http-server in the repo with the default port, I open Tableau, open the Superstore demo dashboard, drag the extension object, and navigate to the Datasources.trex.  After clicking open, Tableau throws an error stating "Error parsing extension manifest" and goes on to list that there is no declaration found for any element or attribute.  I used logviewer to take a closer look and the log shows this:

![image](https://user-images.githubusercontent.com/28812204/40989857-b9546b70-68b4-11e8-97df-e1e4682ed909.png)

It doesn't even look like the manifest is being found.  The log is writing the "file: " instead of "file: datasources.trex".  I verified in the browser that I can manually navigate to directory where the Datasources files are located while the server is running and verified in the manifest that the location was the same as the server.  The error is the same for any of the samples.

**Comment by johnDance** [comment]
Hello!
Thank you for your report.
We will be updating github and the documentation shortly.
This will be included in the documentation:

This release introduces two changes to XML schema for the extensions manifest file (.trex). If you have an existing .trex file, you need to make a couple of corrections.
•	The first change is to the URL of the extensions namespace (xmlns). The URL is now www.tableau.com... instead of wwww.tableau.com...
        <manifest manifest-version="0.1" xmlns="http://www.tableau.com/xml/extension_manifest">
          <dashboard-extension id="com.example.extensions.name" extension-version="0.1.0">
          . . .
•	The second change is to the author’s web site. This link to your web site must now be over HTTPS for security. This link to your web site becomes the Get Support link in the About dialog box for your extension.
        <author name="tableau" email="github@tableau.com" organization="tableau" website="https://www.tableau.com"/>

Those changes should allow the extension to load properly.
Sorry for the inconvenience.
John

**Comment by dkhungry** [comment]
Editing the namespace URL worked and the extension now loads.  Thanks John.
