### ISSUE TITLE
Column isReferenced always returns false

### ISSUE THREAD

**Issue by BobSenturus** [tableau/extensions-api#131]
Example, extending the datasource example code:

For each worksheet, call getDataSourcesAsync.

For each datasource, call getUnderlyingDataAsync 

When looping through the columns in the datatable that is returned, all the columns indicate "isReferenced" is false, even when columns are in use in the associated sheet. Adding and removing columns, then reloading the extension, doesn't seem to change anything.

ref:
https://tableau.github.io/extensions-api/docs/interfaces/column.html#isreferenced

**Comment by KeshiaRose** [comment]
Hi Bob, `isReferenced` only shows as `true` if the column referenced is in the worksheet you used to get the data. If you use getUnderlyingDataAsync from a data source, none of the columns will return `true` because there is no sheet to reference. `isReferenced` is tied to individual worksheets, it does not check if a column in a data source is being used in any worksheets in your workbook.
