### ISSUE TITLE
Dragging Extension on the dashboard freezes Tableau Desktop

### ISSUE THREAD

**Issue by merlijnbuit** [tableau/extensions-api#135]
A customer of us is testing our extensions and is having difficulties with using Tableau Desktop on Citrix. 
When he drags the extension on the canvas Tableau Freezes. He already disabled accelerated graphics.

It looks like this:
![stuck](https://user-images.githubusercontent.com/16118919/42272818-aaeffba0-7f87-11e8-810e-1a6a20c8272c.jpg)

any tips?

**Comment by LGraber** [comment]
Merlin ... my apologies for the *long* overdue response on this. We are going through all of the old items so that we can make sure we stay on top of github reported issues (and not have some long trail left hanging). I assume at this point the issue is either resolved or gone? If you still have this, or ever see it again, the first step would be to look in the log files. All extension related activity is tagged in the log files explicitly so we can see if the extension did something that hung Tableau. Let me know if there is anything left here. Thanks

**Comment by merlijnbuit** [comment]
Hi @LGraber,

Thank you for the follow up! I did not receive the error anymore. If we receive this notification from our customer again I will let you know!

Merlijn
