### ISSUE TITLE
Event listeners not working on Online

### ISSUE THREAD

**Issue by merlijnbuit** [tableau/extensions-api#179]
Hi there,

There is a bug happening on Tableau Server with extensions. It looks like event listeners are not working correct. If you have multiple extensions on the dashboard and you filter the sourcesheets from another sheet (normal tableau actions) you would expect that all extensions on the dashboard update. This is happening on Tableau Desktop, but when you publish it only the first or last extension found by the extension api gets an update by the event listener.

We have a customer which is blocked by this issue. The customer is using 3 radar charts on their dashboard but only one radar chart updates when you select a different customer.

Example:
Radar 1 connected to Sheet 1
Radar 2 connected to Sheet 2
Sheet 3 as filter on Sheet 1 and Sheet 2
![event_not_working](https://user-images.githubusercontent.com/16118919/49936340-f82c2f80-fed3-11e8-995a-0c75f84e0e52.gif)

Thank you

Merlijn

**Comment by johnDance** [comment]
Hi, thank you for the report. 
We have duplicated the issue, and currently investigating. 
I'll report back when we know more.
Thanks again,
John

**Comment by merlijnbuit** [comment]
Thank you John!

**Comment by merlijnbuit** [comment]
Hello John!

Any updates on this issue? It is still blocking our customers dashboard release.

Thanks!

**Comment by johnDance** [comment]
I'm sorry for the delayed reply. I was delaying until I could give you some definite information, but I still can't. :-(

We are currently working on this issue. However, it is inside Tableau rather than our extension code. I'm hoping it will be in 2019.1, but right now I'm not sure if we will make it in time for some upcoming deadlines. Give me a few more days, and I should be able to know better the release that it will be in.

Thanks again,
John

**Comment by johnDance** [comment]
The fix for this will not make it for 2019.1. I'm hoping to get it into 2019.1.1
I know this is disappointing news. I wish I could report something happier.
John

**Comment by merlijnbuit** [comment]
Hello John!

Any updates on this one? :)

**Comment by johnDance** [comment]
Yes! This has been fixed in 2019.2. 2019.2 is getting ready for release. The change was big enough that at the time, we felt it shouldn't go into a maintenance release. Now that it has been active in-house for a while without issues, let me bring that up for discussion again. Thanks for your patience on this one.
John

**Comment by merlijnbuit** [comment]
Great! I will contact my customer and let them know!

**Comment by bcantoni** [comment]
Closing as fixed.
