### ISSUE TITLE
Applying filter using applyFilterAsync breaks session?

### ISSUE THREAD

**Issue by TomNes94** [tableau/extensions-api#190]
I have a selection of marks that are shown at first, and after an action I would like to replace the filter to show only one of the marks in the selection. Performing the code below basically crashes my Tableau.

`        ws.applyFilterAsync("REF_101_Perceelnummer", perceel, "replace").then(result => {
          console.log(result);
        });`

Clicking "About" in the Extensions settings does not work, the debugger in my Chrome browser (http://localhost:8696/) is not responding either. Reloading the extension only gives me a white screen. Extensions only work again after restarting Tableau. This is on Desktop btw.

**Comment by johnDance** [comment]
Tom: 
Sorry for the delay. We have been battling #Snowmaggedon2019 here in the Seattle area. :-)

Is the action happening before you call applyFilterAsync a longer running command? We have found, and fixed, several issues with commands not being synchronized properly. These issues are fixed in 2019.1, coming soon. If that is the problem, there isn't a great way to solve it. You can put a delay before your applyFilterAsync. That would be a short term hack.

John

**Comment by LGraber** [comment]
Hi Tom ... is this still an issue for you? We would need to see a log to get more insight into what might be happening. Let us know so we can figure out if this is still an issue or we should close this out.

**Comment by TomNes94** [comment]
No, its not. You can close it!
