### ISSUE TITLE
Unhandled promise rejection This extension is not running inside an iframe, desktop, or popup window. Initialization failed.

### ISSUE THREAD

**Issue by nguyenmanhha87** [tableau/extensions-api#210]
I ihave nstalled tableau extension but it's not work.
I check console of chrome. "Unhandled promise rejection This extension is not running inside an iframe, desktop, or popup window. Initialization failed."

open http://localhost:8765/Samples/DataSources/datasources.html
=> All DataSources > Loading...

Can you help me to fix it ?

Thank you.

**Comment by johnDance** [comment]
Hello:
What browser are you running in?
What version of tableau server are you using? (I'm assuming you are running server and not desktop.)
Have you modified the datasources sample at all?
John

**Comment by nguyenmanhha87** [comment]
thanks johnDance,

I use the latest Chrome. and tableau desktop 2018.2.

i use latest nodejs

i haven’t modified the datasources sample. 

Could you help me to check log to fix?

Thanks you

**Comment by johnDance** [comment]
Hello
You have your local server up and running, so that is good. However, to use an extension, you need to create a Tableau dashboard, and then drag the extension icon to choose an extension. Then you select the .trex file. At that point, your data sources sample will be running in the Tableau dashboard, and will function properly. This web page has a good explanation on adding the extension with an animated example: https://tableau.github.io/extensions-api/docs/trex_getstarted.html#start-tableau-and-add-an-extension-to-the-dashboard.

John

**Comment by LGraber** [comment]
As John points out, it sounds like what you were trying to do was simply load your extension inside of a browser. That won't work and you will get the exact error you were seeing. let us know if that is what you were doing and if you are now able to use the extension within Tableau (desktop / server). Thanks! I will also look at putting up something in our docs with this error string so people can find it faster.

**Comment by RaghunathVadlakonda** [comment]
I'm also facing the same issue
I'm using tableau desktop, I'm new to Tableau work. May I know what exactly this issue is
![Screenshot 2021-11-08 at 8 49 13 PM](https://user-images.githubusercontent.com/40694784/140768716-7fe85e22-c032-4e86-951b-1d5e4d175a09.png)
![Screenshot 2021-11-08 at 8 49 31 PM](https://user-images.githubusercontent.com/40694784/140768725-ee67c720-76ce-49d9-8716-3553cb7d26a6.png)
?

**Comment by johnDance** [comment]
Hi @RaghunathVadlakonda 
How are you using your extension in your Tableau dashboard? Make sure to drag (or double click) the extension icon in the dashboard objects panel. That will create a new dashboard object that will hold your extension, and will also open up a dialog for you to choose your extension.

If that doesn't work, would it be possible to share a small workbook where you are seeing this problem? 

Thanks,
John

![image](https://user-images.githubusercontent.com/37640168/140783475-2399097a-e712-49e7-95c6-8debc724689e.png)

**Comment by RaghunathVadlakonda** [comment]
Hi @johnDance 

Yes(I used drag), Same I used the extension how you mentioned above.

I'm using Macbook Air - 11.6 version
I tried with 2021.2 and 2020.2 Tableau Desktop versions and Extension version - 1.7.0

Actually, I'm using javascript to create a custom extension and integrate it into Tableau Desktop but When I'm trying to drag extension in the tableau dashboard I'm getting this issue in my chrome browser console
![Screenshot 2021-11-08 at 8 49 13 PM](https://user-images.githubusercontent.com/40694784/141446080-575350e0-7e2f-469f-9239-1aeade49c5ac.png)
.

**Comment by johnDance** [comment]
Hi @RaghunathVadlakonda 
Have you verified that your first extension call is initializeAsync? That needs to happen after the document has loaded. If you don't call initializeAsync, or if initializeAsync is called before the document has been loaded, the next calls will fail.
John
