### ISSUE TITLE
Datavalue in 1.2.0

### ISSUE THREAD

**Issue by tjallingt** [tableau/extensions-api#239]
Sorry to be asking questions in the issues but i'd like some more clarification on the changes made to datavalues in v1.2.0

https://tableau.github.io/extensions-api/docs/interfaces/datavalue.html

Firstly: 

> 1.2.0 Fixes the type to be the raw native value rather than a string.

Am i correct that this fix is on the side of desktop/server and not in the extensions api? More specifically will using extensions api v1.2.0 with desktop 2018.3 (for example) still only give you strings?

Secondly:

> such as '%null%', or '%no-access%'.

This list is not exhaustive right? I am pretty sure i have seen `%missing%` as well for example, is the only way to check for a "special value" by doing:

```ts
function isTableauSpecialValue({ value }: DataValue) {
  return (
    typeof value === "string" && value.startsWith("%") && value.endsWith("%")
  );
}
```

**Comment by johnDance** [comment]
These are great questions.
1. The fix to be the raw type rather than a string for DataValue.value was made both in 1.2 and 2019.2. So the fix will be there in v1.2.0 + 2018.3, or in v1.0.0 + 2019.2.

Having said that, you are correct that the real fix is in desktop/server. The v1.2.0 with 2018.3 will have a little slower performance for very large data tables because it is translating all the values back on the client side.

2. You are correct. %null% and %no-access% are examples. 
The full list is: %null%, %all%, %wildcard%, %skipped%, %no-access%, %ragged%, %error%, %many-values%, %missing%
(Don't ask me what they all mean.)

Your isTableauSpecialValue function will work great. 

Best wishes!
John

**Comment by tjallingt** [comment]
1. Great to hear, free performance boost! That should also mean I can just delete the code that was doing the casting in user space 😄 
    - I'll need to test it regardless but just for confirmation: v1.2.0 with 2018.3 will handle date values correctly in ie11? I found out the hard way that `new Date(myDateString)` is somewhat unreliable/inconsistent in ie11 and I had to fall back to using `date-fns` which implements a custom date string parser in Javascript.
2. Very interesting... good to hear that function will work, I might need to use it to update some extensions 😅

<details>
<summary>for reference: Value casting code I can hopefully delete</summary>

```ts
import parseDate from 'date-fns/parse';
import { Column, DataValue } from '@tableau/extensions-api'; // pls make me a real thing 😭

type ValueParser = (dataValue: DataValue) => any;

export function getValueParser(column: Column): ValueParser {
  switch (column.dataType) {
    case 'date':
    case 'date-time':
      return ({ value }) => parseDate(value);

    case 'float':
      return ({ value }) => {
        let f = Number.parseFloat(value);
        if (Number.isNaN(f)) {
          return null;
        }
        return f;
      };

    case 'int':
      return ({ value }) => {
        let i = Number.parseInt(value);
        if (Number.isNaN(i)) {
          return null;
        }
        return i;
      };

    case 'spatial': // ???
    case 'bool':
    case 'string':
    default:
      return ({ value }) => value;
  }
}
```

**Comment by tjallingt** [comment]
for the sake of completenes: it seems that date/date-time values are still passed as strings:
![image](https://user-images.githubusercontent.com/5736783/61115777-7c0ec000-a493-11e9-9ccd-aebbfb9b3bbd.png)
