### ISSUE TITLE
Sandboxing requirement

### ISSUE THREAD

**Issue by merlijnbuit** [tableau/extensions-api#277]
Hi,

So I am 'playing' (fighting) with the sandboxed extensions and preparing our products for the sandbox gallery. 
![image](https://user-images.githubusercontent.com/16118919/67083626-c642c400-f19b-11e9-8633-1dd63fc096ea.png)

I am wondering if you could the following CSP header for font icons to work properly:

font-src data:

Thanks

**Comment by seanmakesgames** [comment]
Hey Merlijn!

Yeah-- we haven't fully investigated the security holes in data: for the font-src attribute at this time, that's why it's off.
Current workaround is to have fonts packed in as resource files. Is that a workaround that can work for you in this case?

Let me know about the workaround. We'll keep you posted on our results on this.

**Comment by merlijnbuit** [comment]
Hi Sean,

That doesn't work unfortunately. It is a minimum requirement for one of the APIs we use. They have a CSP disclaimer on their website and font-src data: is in it.

Thank you

**Comment by seanmakesgames** [comment]
Ok. We'll take a look and get back to you!

**Comment by seanmakesgames** [comment]
This should be available in tabextsandbox v. 1.1.0 which we just released.
