### ISSUE TITLE
Google Trends iFrame generated by script is not working

### ISSUE THREAD

**Issue by orkusfox** [tableau/extensions-api#348]
Hi 

I would like to embed Google Trends chart into Tableau. I plan to add possibility to use filter values as a keywords.
As a first step I have tested if embed google trend chart is presented properly.

I added html code as a log file (sorry for that but I don't know how to add html code properly in comment)
[googletrends.log](https://github.com/tableau/extensions-api/files/5124050/googletrends.log)

When I checked how it looks like on local server in browser (http://localhost:8765/Samples/GoogleTrends/googletrends.html) it look correct on google chrome. When I checked it on IE11 It is not working. I think that IE11 is used as an html engine for Tableau Extension on my local environment.
info from console in IE11
![image](https://user-images.githubusercontent.com/63920172/91188715-e8796c80-e6f1-11ea-9071-970517726168.png)

I checked that google trends it not working at all on IE11, because IE11 is not a modern webbrowser

Any ideas how could I embed google trends into Tableau and use internal tableau filters as a input for JS script.

Regards
![InformationFlow-Page-2](https://user-images.githubusercontent.com/63920172/91188446-99333c00-e6f1-11ea-97ef-218eae8ca69a.png)

**Comment by johnDance** [comment]
Hi @orkusfox 
Tableau uses chromium as the webengine for desktop. However, the extension is in an iframe, so that might be affecting you somehow. You can debug the extension inside Tableau so that you can see what the issue might be. See https://tableau.github.io/extensions-api/docs/trex_debugging.html for how to set up debugging for either Windows or Mac. 

Hopefully that will help you get running.
John

**Comment by bcantoni** [comment]
Closing out based on age and John's feedback. If this is still an issue, please reopen with a comment on the latest status and we can revisit.
