### ISSUE TITLE
Get data beyond 10,000 rows from extension

### ISSUE THREAD

**Issue by PoojaG20** [tableau/extensions-api#358]
We have more than 10,000 rows in Worksheet or Data source. But while fetching full data, we get only 10000 rows. Without pagination is there any way to get whole data. Wanted to understand the difference it has with respect to Download -> Cross Tab functionality as there it has more than 10,000 rows downloaded.

**Comment by Kovner** [comment]
Yeah, this is an intentional limit we established to prevent massive queries being run by Extensions potentially taking down Tableau Server or Online. The reason it has to have a different behavior than manually querying all of the data is that Extensions allow programmatic access to those queries and it could cause things to get out of hand.
Pagination is definitely the way we need to address this and its something we want to accomplish but unfortunately we don't have a timeline on when we will be able to get it done.

**Comment by PoojaG20** [comment]
So, there is no way to get more data in extension as of now?

**Comment by SiebeG** [comment]
@PoojaG20 

at the best of my knowledge the 10K row limit is solved (expanded) in 2020.2.4 as can be read over here:
https://github.com/tableau/extensions-api/issues/334

So check your Tableau version and maybe upgrading to a recent build can fix your issue

Or are you experiencing a different issue?

**Comment by johnDance** [comment]
@SiebeG is correct, there was a defect in getSummaryData. FIxed in 2020.2.4, getSummaryData will access all rows in your worksheet. However, getUnderlyingData/getLogicalTableDataAsync has a limit of 10k as mentioned by @Kovner.
John

**Comment by venky18** [comment]
The limit is defined by the extension api itself.  You can change the limit to a larger number, I tested up to 100,000 rows and it worked fine but was a bit slow. 

As of today the function is defined in line no13,526 in [here](https://raw.githubusercontent.com/tableau/extensions-api/main/lib/tableau.extensions.1.8.1.js)
```
    GetDataServiceImpl.prototype.getMaxRowLimit = function () {
        return 10000; //change this to 20000,30000...
    };
```

**Comment by johnDance** [comment]
We do not recommend this work around. As @Kovner mentions above, the limit is there for protection of the Tableau server. We are planning on introducing a paging model that would allow you to access all underlying data.
Thanks!
John

**Comment by johnDance** [comment]
We can now read up to 1 million rows of data with a DataTableReader with version 1.10.0 and Tableau 2022.4.
