### ISSUE TITLE
Embedded extensions not respecting the "Hide" login prompt setting

### ISSUE THREAD

**Issue by bcranteverfi** [tableau/extensions-api#461]
**Describe the issue**

Since upgrading servers to 2021.4.2, our Extensions have been displaying the Login modal, despite having all of the User Prompts set to “Hide” in the Extension settings.

**Version information:**
 - Tableau version:  Tableau Server 2021.4.2
 - OS: Tableau Server is on MIcrosoft Windows 2016
 - Browser: Tested on Chrome, Safari, and Mozilla
 - Version: Chrome 97.0.4692.99

**A clear and concise description of what you expected to happen.**

For reference, this is pertinent to our case. Our Tableau Server is hosted on a different domain than where the Extension API is embedded:
https://kb.tableau.com/articles/Issue/embedded-views-fail-to-load-after-updating-to-chrome-80

However, I just tested and this is not limited to Chrome. And obviously, we cannot micromanage Chrome on behalf of our users, or even enforce that they use Chrome to begin with.

Our infrastructure team have requirements that make them opposed to enabling SSL as that article suggests. That is also not a trivial thing to test. If I could have guarantees that enabling SSL would resolve this problem, I could make the case to the infrastructure team. I would love to hear more about whether or not that is an accurate diagnosis!

**If possible, attach a workbook with sample data add/or screenshots to help explain your problem.**
I can share the Extension privately if that would be helpful. Here are screenshots:
![extension_settings](https://user-images.githubusercontent.com/83613266/151853926-f7206028-4d26-4af9-9025-a224e84104af.png)
![user_prompts](https://user-images.githubusercontent.com/83613266/151853927-d309aa2d-f51a-4fac-8070-2689afab14d4.png)

**Comment by johnDance** [comment]
@bcranteverfi : Thanks for your report. We have duplicated this in-house, and it is a high priority to fix immediately.
John

**Comment by johnDance** [comment]
Logged internally as #1369679

**Comment by johnDance** [comment]
@bcranteverfi 
It turns out that on the same day as you reported, there was another report about a permissions dialog. We mistakenly combined the two issues into a single one. When you say the "login model" are you referring to the extension permission dialog, or logging into Tableau Server? It appears that your second attachment is an embedded Tableau scenario. Is this where you are getting the login? If so, that is unrelated to your dashboard extensions settings. Below is what the extension permission prompt looks like. This is shown or hidden based on the settings you highlight above.

Thank you, and sorry for the confusion.
John

<img width="605" alt="Screen Shot 2022-02-01 at 4 53 45 PM" src="https://user-images.githubusercontent.com/37640168/152076261-c5eacf78-40f7-415c-bd10-d0c1aaf3c315.png">

**Comment by bcranteverfi** [comment]
@johnDance Hey John, sorry for slow reply, I just moved to Phoenix and have been out this week.

Circling back here, my mistake on the premise of the issue. I have only ever seen the "Allow Extension" modal that you posted in Tableau Desktop, not the embedded Extension, so the "Hide" setting is operating as expected on the Server.

I will reach out to the Embedded team for further guidance.

Thanks again for your help!
