### ISSUE TITLE
Proposal:  Security model

### ISSUE THREAD

**Issue by benlower** [tableau/extensions-api#66]
- Extensions must declare, in the manifest, if they intend to access underlying data or datasource information. The API will enforce that if the Extension did not declare underlying data access, it will not be able to make those calls.
- In Desktop, when adding a new Extension, if the Extension requests underlying data access, the user will be prompted to allow/disallow the Extension.
- In Desktop, when opening an existing workbook, the user will be prompted. This prompt will inform the user if the Extension accesses underlying data access, and will ask the user to allow/disallow the Extension (whether it accesses underlying data or not).
- In Server, in the site settings page, admins will control a list of safe-listed domains. Extensions that are from domains that are not in this safe-list will not load.
- Each entry in the safe-list will have a checkbox to allow/disallow Underlying Data Access. Extensions that request Underlying Data Access, but that are not safe-listed for Underlying Data Access will not load.
- Each entry in the safe-list will have a checkbox to suppress prompts. If an Extension is safe-listed but prompts are not suppresses, Server Interactors will be prompted when loading workbooks that contain those Extensions. If an Extension is safe-listed with suppress-prompts, Interactors will not be prompted. 
- The default for the safe-list is "https://*" ; No Underlying Data Access ; Do not Suppress Prompts. That is, all Extensions that do not request Underlying Data Access will work by default, but they will prompt. From there, admins can add domains that are allowed to access underlying data, or for which prompts should be suppressed. The admin can also delete this default entry to disallow all extensions (and then they can safe-list one-by-one).

**Comment by datocrats-org** [comment]
- It would be helpful to selectively permit specific columns and/or tables to be visible to the user through such methods, instead of adopting an all or nothing approach.  Elsewhere this is called perspectives.  
- If you think of Tableau as a front-end to an organization's data (warehoused in any form), dashboards can help users locate specific data sets of interest. Ultimately they will have to go P2P to find the data they need.  
- Setting up perspectives or letting a user browse to propose a perspective _without seeing the full data set_ would be useful in organizations with strict access polices. 
- If I need to build extension that will allow exporting subsets of data displayed in dashboard form with some other JS method, that's fine too.  Restricting the tunnel to the underlying data is a good idea.  But, designing a carefully managed way to track down data sets of interest would be even more helpful to dashboard consumers.  
  - Let the user pick and choose from what's available without seeing all of the data in raw format (dashboards show it in graph format). 

Related to this, Tableau has limits on what I can or can't do with primary and secondary data sources (blended or joined datasets, mix of geospatial and fact tables from separate data sources). Having an all or nothing approach in what I can see using the View Underlying Data command is already very limiting as discussed here https://community.tableau.com/thread/126087

**Comment by Kovner** [comment]
@datocrats-org If I'm understanding you correctly, you would want the owner of a datasource or admin to define which users have access to which columns in that datasource? Is that right? And you would want this to apply not just for the API but querying the datasource with Tableau in general?

**Comment by datocrats-org** [comment]
Yes that’s right

**Comment by bcantoni** [comment]
Closing out based on age. If this is still an issue, please reopen with a comment on the latest status and we can revisit.
